const DEFAULT_PROCESSED_TABLE = 'PATAGONIA.CORE_TEST.ERP_PROCESSED_SALESLINE';
const DEFAULT_ACCOUNTING_TABLE = 'PATAGONIA.CORE_TEST.ERP_ACCOUNTING_TRANSACTION';

export const PROCESSED_SALESLINE_TABLE = process.env.SNOWFLAKE_PROCESSED_TABLE || DEFAULT_PROCESSED_TABLE;
export const ACCOUNTING_TRANSACTION_TABLE = process.env.SNOWFLAKE_BASE_TABLE || DEFAULT_ACCOUNTING_TABLE;
